import unittest
from parameterized import parameterized

from katas.password_validation.password_validation import password_validation

class PasswordValidation(unittest.TestCase):

    @parameterized.expand(
        [
            ('fjd3IR9', True),
            ('ghdfj32', False),
            ('DSJKHD23', False),
            ('dsF43', False),
            ('4fdg5Fj3', True),
            ('DHSJdhjsU', False),
            ('fjd3IR9.;', False),
            ('fjd3  IR9', False),
            ('djI38D55', True),
            ('a2.d412', False),
            ('JHD5FJ53', False),
            ('!fdjn345', False),
            ('jfkdfj3j', False),
            ('123', False),
            ('abc', False),
            ('123abcABC', True),
            ('ABC123abc', True),
            ('Password123', True),
            ("PA9fNIxYy", True),
            ("dQCq+7", False),
            ("tpuJB+9u8yAJPS", False),
            ("7e6Y4QIJzH", True),
            ("59WDeZ", True),
            ("7xAx4ABpITE", True),
            ("jvi3odpn8um5OjgZHp", True),
            ("xlYJGjhw8I", True),
            ("3dkIy4rC9Wzq", True),
            ("F0493MXtD", True),
            ("waQn9Y7yh", True),
            ("0mioY9PQC", True),
            ("T3a", False),
            ("ScXCJ2", True),
            ("X_CahdST73", False),
            ("gHVH5Rk", True),
            ("W?twW0C", False),
            ("SES8ggY", True),
            ("8Ds", False),
            ("Qlt0t7obpjy7Pd", True),
            ("xNDGKrD1maw0\\vib1", False),
            ("5rD1GD6v4G2MV5WQ", True),
            ("Q60iH9jFli", True),
            ("4ulg0pM_", False),
            ("BBa06T0t7Hmx64", True),
            ("vIo5WI8p3MT", True),
            ("cFs+s\\9E+V15M", False),
            ("S1myF-85A7usrsC", False),
            ("KRKk0/zpqc88e", False),
            ("5kE", False),
            ("58Luj", False),
            ("sLSakgA-KytQVY0", False),
            ("W9j", False),
            ("1r!h8WQ", False),
            ("W5eerc", True),
            ("H0QGLe/uYcb5", False),
            ("9d7ok5jOKvbLeIK", True),
            ("iE0x", False),
            ("NfH1Csg4ZE!NDwWBXO", False),
            ("FYja0smngO7WY", True),
            ("O4IRWh-nummscBLQ", False),
            ("U12QBup3aVqw", True),
            ("Adz3YscLTy2rmvi", True),
            ("yP7", False),
            ("gl3nX5s5Pa", True),
            ("yB6y1", False),
            ("6dHGn+QyLBuAJm/6a", False),
            ("FJi4H6AiwDCRMM", True),
            ("wP1XtbzyUqgZmrQ8Jb", True),
            ("PvyHokZzbS3jD7f", True),
            ("JCZ?O2U6mreM", False),
            ("cWP5FMj", True),
            ("V5GYSTfU0", True),
            ("8ugH6sOA", True),
            ("K1nqVFBg8mhAab-k", False),
            ("6F9h", False),
            ("6RMeoH", True),
            ("I7Yj", False),
            ("76YDLCS48pdy", True),
            ("IGIytpD1XA2uN", True),
            ("tHbcXvHgGk-42Gxe3K", False),
            ("jOrHrH2si", True),
            ("UnncSY0-N1Kw", False),
            ("6qf\\BD", False),
            ("21h/a2\\KR9liCjR", False),
            ("/7fTXOItcK4Wmzki", False),
            ("8Mr", False),
            ("8k17OFjE", True),
            ("Q2oWF+?TiXF96yhO/", False),
            ("ZZy1i_18", False),
            ("0Yo6SON", True),
            ("l0aK4PvMb4wN7", True),
            ("hLfWRg9Y\\paf0dz", False),
            ("UVt3Z", False),
            ("plnBzR0NZG9F6ZSw", True),
            ("be1L8Hnx0HDcB8", True),
            ("rMPs5wi-r0M9rX7m?", False),
            ("P1ROv?Z14", False),
            ("tJOz1FvT2rq", True),
            ("O5qPV8", True),
            ("Rk7pX41U/eFfqVda", False),
            ("E6\\9J6/am-41End2P", False),
            ("6LVl", False),
            ("XYlbJDYE4OE5OcvQAL", True),
            ("G40CCUX/4uu", False),
            ("7Tn", False),
            ("W9h7p+", False),
            ("barPui?txC6hS", False),
            ("QU4dc8j", True),
            ("eN1oV7kKRPcrzUAw", True),
            ("v3o-\\0-nfF0n", False),
            ("+kL9sC", False),
            ("OwLuRNZ1q5MwwNFG", True),
            ("8rO", False),
            ("O0a", False),
            ("2wWSCpgrIJvz", True),
            ("9bJ", False),
            ("5+P0j1Jxh", False),
            ("YDdFJq6j90z", True),
            ("z3ePxa", True)
        ]
    )
    def test_password_validation(self, password, result):
        ""
        assert(password_validation(password)) == result